### ISSUE TITLE
Add support for folders

### ISSUE THREAD

**Issue by goodness-from-me** [futo-org/grayjay-plugin-spotify#2]
Spotify plugin does not currently support folders in any shape or form.
In Spotify you can organise your playlists into folders.
The code currently does not handle folders at all.

**Comment by goodness-from-me** [comment]
One of the side-effects of this issue is that import is broken for me.
Cannot import anything from my Spotify account.
The error is:
```
[Spotify] unreachable (2610)[24-25]
source.getUserSubscriptions(...)
```
And the same kind of error on importing playlists.
I did some plugin debugging and saw that the error comes from not handling `case "Folder":` playlist type in `getUserPlaylists` and `getUserSubscriptions`

**Comment by support-grayjay** [comment]
@goodness-from-me Could you please open a separate issue for the importing bug if it is still affecting you?
Could you also please open it over at https://github.com/futo-org/grayjay-android/issues since all of the issues related to the Grayjay get reported there anyway?

**Comment by kaidelorenzo** [comment]
This should be fixed by a Spotify plugin update I released a few weeks ago.

https://gitlab.futo.org/videostreaming/plugins/spotify/-/commit/2d660dc8302b4f57283a39a137bf1925651f35f2

**Comment by goodness-from-me** [comment]
@kaidelorenzo yes, it is fixed. Thank you! Closing the issue.
